services:
  api:
    image: ghcr.io/mohamm4c/multi-server:latest
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
    restart: unless-stopped

  client:
    image: ghcr.io/mohamm4c/multi-client:latest
    restart: unless-stopped

  worker:
    image: ghcr.io/mohamm4c/multi-worker:latest
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    restart: unless-stopped

  nginx:
    image: ghcr.io/mohamm4c/multi-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - client
      - api
    restart: unless-stopped
