services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres
    restart: unless-stopped
  redis:
    image: 'redis:latest'
    restart: unless-stopped

  api:
    image: ghcr.io/mohamm4c/multi-server:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
  client:
    image: ghcr.io/mohamm4c/multi-client:latest
  worker:
    image: ghcr.io/mohamm4c/multi-worker:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped
  nginx:
    image: ghcr.io/mohamm4c/multi-nginx:latest
    ports:
      - '3050:80'
    depends_on:
      - client
      - api
    restart: unless-stopped